#!/usr/bin/env python3
"""Deterministic session handoff writer for long-running workflows.

Writes a complete YAML snapshot to ``working/session_state.yaml`` so a future
session can resume without losing local artifacts or external resource IDs.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

SECRET_MARKERS = ("password", "token", "secret", "api_key", "apikey", "private_key")
REQUIRED_TOP_LEVEL = ("dataset", "task", "resources", "pipeline", "local_files", "auth", "issues", "resume")


def redact_secrets(value: Any) -> Any:
    """Recursively redact secret-looking keys and scalar values."""
    if isinstance(value, dict):
        out = {}
        for key, val in value.items():
            key_str = str(key)
            if any(marker in key_str.lower() for marker in SECRET_MARKERS):
                out[key] = "<redacted>"
            else:
                out[key] = redact_secrets(val)
        return out
    if isinstance(value, list):
        return [redact_secrets(v) for v in value]
    if isinstance(value, str) and any(marker in value.lower() for marker in ("bearer ", "sk-", "xoxb-")):
        return "<redacted>"
    return value


def default_state(
    *,
    dataset: str = "unknown",
    task: str = "unspecified",
    next_step: str = "review session state and continue",
    now: str | None = None,
) -> dict[str, Any]:
    """Return a complete session handoff structure with safe defaults."""
    timestamp = now or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return {
        "_comment": "Session State — auto-generated by session-handoff skill",
        "last_updated": timestamp,
        "dataset": dataset,
        "task": task,
        "resources": {
            "google_doc": {"id": None, "title": None, "url": None, "status": "not used"},
            "google_slides": {"id": None, "title": None, "url": None, "status": "not used"},
            "notion_page": {"id": None, "title": None, "url": None, "status": "not used"},
            "drive_files": [],
        },
        "pipeline": {
            "run_id": None,
            "run_dir": None,
            "last_completed_step": "unknown",
            "current_step_status": "unknown",
            "next_step": next_step,
            "steps_remaining": [next_step],
        },
        "local_files": {"outputs": [], "working": [], "charts": [], "data": []},
        "auth": {
            "google_email": "unknown — verify at resume",
            "notion_workspace": "unknown — verify at resume",
            "last_verified": "unknown",
            "notes": "Verify auth before external resource operations.",
        },
        "issues": ["None — all work completed successfully"],
        "resume": {
            "command": "$resume-pipeline",
            "steps": [
                "Read working/session_state.yaml",
                "Verify auth and external resources",
                f"Continue from: {next_step}",
            ],
        },
    }


def merge_state(base: dict[str, Any], updates: dict[str, Any] | None = None) -> dict[str, Any]:
    """Deep-merge updates into base, returning a redacted copy."""
    def merge(a: Any, b: Any) -> Any:
        if isinstance(a, dict) and isinstance(b, dict):
            result = dict(a)
            for key, val in b.items():
                result[key] = merge(result.get(key), val) if key in result else val
            return result
        return b if b is not None else a

    return redact_secrets(merge(base, updates or {}))


def validate_state(state: dict[str, Any]) -> list[str]:
    """Return validation errors for a handoff state."""
    errors = []
    for key in REQUIRED_TOP_LEVEL:
        if key not in state:
            errors.append(f"Missing top-level key: {key}")
    if state.get("resources") is not None and not isinstance(state.get("resources"), dict):
        errors.append("resources must be a mapping")
    if state.get("pipeline") is not None and not isinstance(state.get("pipeline"), dict):
        errors.append("pipeline must be a mapping")
    if state.get("local_files") is not None and not isinstance(state.get("local_files"), dict):
        errors.append("local_files must be a mapping")
    issues = state.get("issues")
    if issues is not None and not isinstance(issues, list):
        errors.append("issues must be a list")
    return errors


def write_session_state(
    state: dict[str, Any],
    *,
    root: str | Path = ".",
    path: str | Path | None = None,
) -> Path:
    """Validate and write session state YAML, returning the written path."""
    target = Path(path) if path is not None else Path(root) / "working" / "session_state.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    state = redact_secrets(state)
    errors = validate_state(state)
    if errors:
        raise ValueError("Invalid session state: " + "; ".join(errors))
    target.write_text(yaml.safe_dump(state, sort_keys=False, allow_unicode=True))
    return target


def create_and_write(
    *,
    root: str | Path = ".",
    dataset: str = "unknown",
    task: str = "unspecified",
    next_step: str = "review session state and continue",
    updates: dict[str, Any] | None = None,
) -> Path:
    """Create a default handoff, merge updates, and write it."""
    state = merge_state(default_state(dataset=dataset, task=task, next_step=next_step), updates)
    return write_session_state(state, root=root)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--dataset", default="unknown")
    parser.add_argument("--task", default="unspecified")
    parser.add_argument("--next-step", default="review session state and continue")
    args = parser.parse_args()
    path = create_and_write(root=args.root, dataset=args.dataset, task=args.task, next_step=args.next_step)
    print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
